### PR TITLE
EVG-16501: fix e2e error message test

### PR DESCRIPTION
**Pull request by Kimchelly**
Jira: https://jira.mongodb.org/browse/EVG-16501

### Description
From the original PR - update the e2e Spruce test that depended on looking for an exact error message string.

### Screenshots
N/A

### Testing
e2e test should pass.

### Evergreen PR
https://github.com/evergreen-ci/evergreen/pull/5940

### CODE REVIEW

**Review by minnakt — APPROVED** [review]
This is failing because of [EVG-17375](https://jira.mongodb.org/browse/EVG-17375), if you want you can check in a `set-module` patch!

however I believe 🙏

**Comment by Kimchelly** [comment]
I tried running a Spruce patch with set-module but I couldn't figure out how to get it to use the latest commit in the Evergreen repo... ¯\\\_(ツ)\_/¯
`check_codegen` is also failing with `src/gql/generated/types.ts is not up to date`. It seems irrelevant, but I can't really tell?

**Comment by minnakt** [comment]
I ran a patch [here](https://spruce.mongodb.com/version/632b7dcd0ae6062d4684272a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)!

For the codegen task, I think if you merged `main`, it would probably pass!

**Comment by minnakt** [comment]
evergreen retry

**Comment by minnakt** [comment]
For `set-module` I did this:

```
cd spruce
evergreen patch

cd evergreen
evergreen set-module -i <patch_id> -m evergreen
```

**Pull request merged**
