### PR TITLE
EVG-15895 Add Jest and Cypress configs to our eslint configs

### PR DESCRIPTION
**Pull request by khelif96**
[EVG-15895](https://jira.mongodb.org/browse/EVG-15895)

### Description 
I came across the [Jest Eslint Plugin](https://www.npmjs.com/package/eslint-plugin-jest) and i'm pretty surprised we didn't have it. After installing it caught a bunch of issues with our tests. 
Ranging From stylistic issues, to incorrect usage of jest methods, to invalid tests that don't actually test anything. 
I also took the opportunity to install the [Cypress Eslint Plugin](https://www.npmjs.com/package/eslint-plugin-cypress)
Which also did the same. 
Allot of the changes to the tests were fixed automatically by running `eslint-fix` But some were manual (mainly fixing test cases and making better assertions) 

I also split up the Eslint config.
A generic base Eslint config that contains shared configurations for the entire project.
A Eslint config for the `src/` directory which contains react specific configurations and jest configurations
A Eslint config for the `cypress/` directory which contains cypress specific configurations.

Made some changes to the `eslint-staged` config so it applies the correct config depending on the directory the staged file is in.

### CODE REVIEW

**Review by sophstad — COMMENTED** [review]
Are the test failures related to [BUILD-14325](https://jira.mongodb.org/browse/BUILD-14325)?

**Comment by khelif96** [comment]
> Are the test failures related to [BUILD-14325](https://jira.mongodb.org/browse/BUILD-14325)?

Yup! The version of nodejs we use on CI isn't compatible with the latest version of `eslint-plugin-jest`.

**Review by sophstad — COMMENTED** [review]
What do you think of adding an "engines" section to our package.json now that we have an additional node requirement? https://classic.yarnpkg.com/en/docs/package-json#toc-engines

**Review by sophstad — APPROVED** [review]
Nice work!

**Pull request merged**
