### PR TITLE
EVG-12889: Simplify GQLWrapper and decrease the number of renders

### PR DESCRIPTION
**Pull request by SupaJoon**
https://jira.mongodb.org/browse/EVG-12889
these code changes remove unnecessary async syntax, decrease the number of GQLWrapper renders from 3 to 2 and replace an `a` tag with a react router link

### CODE REVIEW

**Comment by SupaJoon** [comment]
evergreen retry

**Review by malikchaya2 — APPROVED** [review]
This is really cool!

**Review by tgrander — COMMENTED** [review]
how many number of rerenders do these changes decrease it by?

**Comment by SupaJoon** [comment]
> how many number of rerenders do these changes decrease it by?

3 to 2

**Comment by tgrander** [comment]
> > how many number of rerenders do these changes decrease it by?
> 
> 3 to 2

Cool so renders go from 2 to 3, saving a total of 1 render. Were you able to tie this 1 less render to any performance benefits to the end user?

**Comment by SupaJoon** [comment]
> > > how many number of rerenders do these changes decrease it by?
> > 
> > 
> > 3 to 2
> 
> Cool so renders go from 2 to 3, saving a total of 1 render. Were you able to tie this 1 less render to any performance benefits to the end user?

the benefit of this PR is meant to resolve tech debt, benefit developers and keep our data flow logical and consistent. I mentioned the render count because saving 1 render indicates that we removed a superflous step in our data flow (by removing removing code) which makes our code easier to debug, extend and maintain as we move forward

**Comment by SupaJoon** [comment]
evergreen retry

**Pull request merged**
