### PR TITLE
EVG-7311: only import required antd css

### PR DESCRIPTION
**Pull request by SupaJoon**
https://jira.mongodb.org/browse/EVG-7311
Screen Shot 2020-05-14 at 3 04 33 PM

### CODE REVIEW

**Comment by SupaJoon** [comment]
`use-babel-plugin-import` requires us to install `react-app-rewired` to override the babel config. This is not ideal because because we will lose the "guarantees" CRA provides. https://github.com/timarney/react-app-rewired#rewire-your-app-

**Comment by tgrander** [comment]
i'm not sure this is the best way to do this either

**Comment by SupaJoon** [comment]
@tgrander These code changes reduce the bundle size by ~4% which is significant. I don't see an issue with maintaining a list of styles for the limited number of antd components we use.

**Comment by tgrander** [comment]
there are test failures that are unusual

**Pull request merged**
