### PR TITLE
EVG-16689: Upgrade LG Radio Group to remove console error

### PR DESCRIPTION
**Pull request by minnakt**
[EVG-16689](https://jira.mongodb.org/browse/EVG-16689)

### Description 
The following error was occurring when interacting with the Chart Toggle on the Project Health page:

image

This was an error also noticed by other LG users. The error was addressed in [PD-1485](https://jira.mongodb.org/browse/PD-1485). 

If you click on the code sandbox in the ticket and change the `leafygreen-ui/radio-group` version to `v7.0.5` (our current version), you will see that this error occurs. If you change the version to `v7.0.6`, the error no longer occurs. For this reason I upgraded our dependency to `v7.0.6` so that the error would be removed.

### Note
There is a way to remove the error on our current version by making use of the `checked` prop on the `Radio` component (see docs [here](https://www.mongodb.design/component/radio-group/documentation/)), but I thought it would be simpler to just upgrade.

### Screenshots
https://user-images.githubusercontent.com/47064971/164031748-ec3186cb-9a4d-4d56-b089-d660105bb8df.mov

### CODE REVIEW

**Review by sophstad — APPROVED** [review]
😎

**Comment by khelif96** [comment]
I'm not sure how this fixes the issue. Since all the patch change did was add a dependency to the package.json without making any functionality changes.
https://github.com/mongodb/leafygreen-ui/commit/6041b89bf5f9dc1e5ea76018bc2cd84bc1fd6faf
https://github.com/mongodb/leafygreen-ui/blob/main/packages/radio-group/CHANGELOG.md#706

**Comment by minnakt** [comment]
> I'm not sure how this fixes the issue. Since all the patch change did was add a dependency to the package.json without making any functionality changes. [mongodb/leafygreen-ui@6041b89](https://github.com/mongodb/leafygreen-ui/commit/6041b89bf5f9dc1e5ea76018bc2cd84bc1fd6faf) https://github.com/mongodb/leafygreen-ui/blob/main/packages/radio-group/CHANGELOG.md#706

I don't know if the CHANGELOG reflects all of the changes, but the ticket was resolved on August 27, 2021.

`v7.0.5` was released on July 19, 2021 so I think it's safe to assume it does not include the changes from the ticket.
Screen Shot 2022-04-19 at 2 51 14 PM

`v.7.0.6` was released on October 11th, 2021, so it most likely includes those changes.
Screen Shot 2022-04-19 at 2 51 19 PM

Besides that, here's a [Slack thread](https://mongodb.slack.com/archives/CFFA5BS79/p1627418691278800) from a user who ran into a similar issue where it says that the problem is most likely resolved by the completion of [PD-1485](https://jira.mongodb.org/browse/PD-1485)

**Comment by sophstad** [comment]
Looks like it's just missing from the changelog: https://github.com/mongodb/leafygreen-ui/commit/c61f0387dec969f66f10579337033cd52db069e0

**Comment by khelif96** [comment]
> > I'm not sure how this fixes the issue. Since all the patch change did was add a dependency to the package.json without making any functionality changes. [mongodb/leafygreen-ui@6041b89](https://github.com/mongodb/leafygreen-ui/commit/6041b89bf5f9dc1e5ea76018bc2cd84bc1fd6faf) https://github.com/mongodb/leafygreen-ui/blob/main/packages/radio-group/CHANGELOG.md#706
> 
> I don't know if the CHANGELOG reflects all of the changes, but the ticket was resolved on August 27, 2021.
> 
> `v7.0.5` was released on July 19, 2021 so I think it's safe to assume it does not include the changes from the ticket. Screen Shot 2022-04-19 at 2 51 14 PM
> 
> `v.7.0.6` was released on October 11th, 2021, so it most likely includes those changes. Screen Shot 2022-04-19 at 2 51 19 PM
> 
> Besides that, here's a [Slack thread](https://mongodb.slack.com/archives/CFFA5BS79/p1627418691278800) from a user who ran into a similar issue where it says that the problem is most likely resolved by the completion of [PD-1485](https://jira.mongodb.org/browse/PD-1485)



> Looks like it's just missing from the changelog: [mongodb/leafygreen-ui@c61f038](https://github.com/mongodb/leafygreen-ui/commit/c61f0387dec969f66f10579337033cd52db069e0)

Great Find! 🕵️

**Pull request merged**
